### ISSUE TITLE
Please fix network packets of client-side and server-side, Exception issue form the while using item (FireSticks) on the physical service-side and logical service-side

### ISSUE THREAD

**Issue by Twlilght-Dream-Of-Magic** [vadis365/PrimalTech#22]
# Title: Please fix network packets of client-side and server-side, Exception issue form the while using item (FireSticks) on the physical service-side and logical service-side

(Identical exception to previous issue) (Fork issus)
#18

Modpack SevTech: Ages 3.0.7
Mod Version: PrimalTech 0.3.2

## Debug Log
`
java.lang.RuntimeException: Missing
at net.minecraftforge.fml.server.FMLServerHandler.getClientToServerNetworkManager(FMLServerHandler.java:298) ~[FMLServerHandler.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.getClientToServerNetworkManager(FMLCommonHandler.java:554) ~[FMLCommonHandler.class:?]
at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$8.selectNetworks(FMLOutboundHandler.java:248) ~[FMLOutboundHandler$OutboundTarget$8.class:?]
at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:297) ~[FMLOutboundHandler.class:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[minecraft_server.1.12.2.jar:?]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[minecraft_server.1.12.2.jar:?]
at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:289) [SimpleNetworkWrapper.class:?]
at primal_tech.items.ItemFireSticks.func_77663_a(ItemFireSticks.java:83) [ItemFireSticks.class:?]
at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526) [aip.class:?]
at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363) [aec.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511) [aed.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) [vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zil000(NetHandlerPlayServer.java:2036) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
`

**Comment by Twlilght-Dream-Of-Magic** [comment]
https://github.com/vadis365/PrimalTech/blob/master/src/main/java/primal_tech/items/ItemFireSticks.java

	@Override //Line 39
	public void onUpdate(ItemStack stack, World world, Entity entity, int itemSlot, boolean isSelected) {
		if (hasTag(stack)) {
			if (!isSelected) {
				if (stack.getTagCompound().getInteger("rubbingCount") != 0)
					stack.getTagCompound().setInteger("rubbingCount", 0);
				if (stack.getTagCompound().getBoolean("animate"))
					stack.getTagCompound().setBoolean("animate", false);
			}
		}
		if (entity instanceof EntityPlayer) {
			EntityPlayer player = (EntityPlayer) entity;
			ItemStack mainHandItem = player.getHeldItem(EnumHand.MAIN_HAND);
			ItemStack offHandItem = player.getHeldItem(EnumHand.OFF_HAND);
			if (!mainHandItem.isEmpty() && !offHandItem.isEmpty()) {
				if (mainHandItem.getItem() == PrimalTech.FIRE_STICKS && offHandItem.getItem() == PrimalTech.FIRE_STICKS) {
					int count = mainHandItem.getTagCompound().getInteger("rubbingCount");
					if (mainHandItem.getTagCompound().getBoolean("animate")) {
						mainHandItem.getTagCompound().setInteger("rubbingCount", mainHandItem.getTagCompound().getInteger("rubbingCount") + 1);
						
						if (count == 10 || count == 30 || count == 50) {
							if (player.world.isRemote)
								player.swingArm(EnumHand.OFF_HAND);
						}

						if (count == 20 || count == 40 || count == 60) {
							if (player.world.isRemote)
								player.swingArm(EnumHand.MAIN_HAND);
						}
					}
					if (count >= 60) {
						mainHandItem.getTagCompound().setInteger("rubbingCount", 0);
						mainHandItem.getTagCompound().setBoolean("animate", false);

						RayTraceResult mop = this.rayTrace(world, player, false);
						if (mop != null && mop.typeOfHit == RayTraceResult.Type.BLOCK) {
							BlockPos clickPos = mop.getBlockPos();
							if (world.isBlockModifiable(player, clickPos)) {
								BlockPos targetPos = clickPos.offset(mop.sideHit);
								if (player.canPlayerEdit(targetPos, mop.sideHit, mainHandItem))
/* 
Why do you write code like this? This is stupid.
It is the physical server, the source of the problem of abnormal stuck. 
*/
									PrimalTech.NETWORK_WRAPPER.sendToServer(new FireSticksMessage(player, targetPos));
							}
						}
					}
				}
			}
		}
	}

**Comment by Twlilght-Dream-Of-Magic** [comment]
[FireSticksMessage.java](https://github.com/vadis365/PrimalTech/blob/master/src/main/java/primal_tech/network/FireSticksMessage.java)

public class FireSticksMessage implements IMessage {

	public int dimension, entityID, buttonID;
	public BlockPos tilePos;

	public FireSticksMessage() {
	}

	public FireSticksMessage(EntityPlayer player, BlockPos pos) {
		dimension = player.dimension;
		entityID = player.getEntityId();
		tilePos = pos;
	}

	public FireSticksMessage(EntityPlayer player, int x, int y, int z) {
		dimension = player.dimension;
		entityID = player.getEntityId();
		tilePos = new BlockPos(x, y, z);
	}

	@Override
	public void toBytes(ByteBuf buf) {
		buf.writeInt(dimension);
		buf.writeInt(entityID);
		PacketUtils.writeBlockPos(buf, tilePos);
	}

	@Override
	public void fromBytes(ByteBuf buf) {
		dimension = buf.readInt();
		entityID = buf.readInt();
		tilePos = PacketUtils.readBlockPos(buf);
	}
}

**Comment by Twlilght-Dream-Of-Magic** [comment]
[FireSticksPacketHandler.java](https://github.com/vadis365/PrimalTech/blob/master/src/main/java/primal_tech/network/FireSticksPacketHandler.java)

public class FireSticksPacketHandler implements IMessageHandler<FireSticksMessage, IMessage> {

	@Override
	public IMessage onMessage(final FireSticksMessage message, MessageContext ctx) {

		final World world = DimensionManager.getWorld(message.dimension);

		if (world == null)
			return null;

		else if (!world.isRemote)
			if (ctx.getServerHandler().playerEntity.getEntityId() == message.entityID) {
				final EntityPlayerMP player = ctx.getServerHandler().playerEntity;
				player.getServer().addScheduledTask(new Runnable() {
					public void run() {
						world.playSound((EntityPlayer)null, message.tilePos, SoundEvents.ITEM_FIRECHARGE_USE, SoundCategory.BLOCKS, 0.2F, 0.1F + (world.rand.nextFloat() - world.rand.nextFloat()) * 0.8F);
						world.setBlockState(message.tilePos, Blocks.FIRE.getDefaultState(), 11);
						ItemStack mainHandItem = player.getHeldItem(EnumHand.MAIN_HAND);
						ItemStack offHandItem = player.getHeldItem(EnumHand.OFF_HAND);
						if (!mainHandItem.isEmpty() && !offHandItem.isEmpty()) {
							mainHandItem.shrink(1);
							offHandItem.shrink(1);
						}
					}
				});
			}
		return null;
	}
}

**Comment by vadis365** [comment]
Thanks for wanting to help out. I appreciate it. No, really. I mean why wouldn't? I enjoy being called stupid and that my code is bad by random people. It really makes me want to improve, get better and continue making things. Making that method Client side only in an annotation is not the way to fix the issue you are having. Adding a check if it's a client side for the world object before the packet is sent is. I must have missed it out when I was stupidly banging my head on the keyboard hoping random collections of letters, numbers and symbols would magically become a mod.
